// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package com.strongsalt.strongdoc.sdk.proto;

public final class Search {
  private Search() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SearchReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The search query.
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The query.
     */
    java.lang.String getQuery();
    /**
     * <pre>
     * The search query.
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    com.google.protobuf.ByteString
        getQueryBytes();
  }
  /**
   * Protobuf type {@code proto.SearchReq}
   */
  public  static final class SearchReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SearchReq)
      SearchReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchReq.newBuilder() to construct.
    private SearchReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchReq() {
      query_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              query_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_SearchReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_SearchReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.strongsalt.strongdoc.sdk.proto.Search.SearchReq.class, com.strongsalt.strongdoc.sdk.proto.Search.SearchReq.Builder.class);
    }

    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile java.lang.Object query_;
    /**
     * <pre>
     * The search query.
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The query.
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The search query.
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getQueryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getQueryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.strongsalt.strongdoc.sdk.proto.Search.SearchReq)) {
        return super.equals(obj);
      }
      com.strongsalt.strongdoc.sdk.proto.Search.SearchReq other = (com.strongsalt.strongdoc.sdk.proto.Search.SearchReq) obj;

      if (!getQuery()
          .equals(other.getQuery())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.strongsalt.strongdoc.sdk.proto.Search.SearchReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SearchReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SearchReq)
        com.strongsalt.strongdoc.sdk.proto.Search.SearchReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_SearchReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_SearchReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.strongsalt.strongdoc.sdk.proto.Search.SearchReq.class, com.strongsalt.strongdoc.sdk.proto.Search.SearchReq.Builder.class);
      }

      // Construct using com.strongsalt.strongdoc.sdk.proto.Search.SearchReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        query_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_SearchReq_descriptor;
      }

      @java.lang.Override
      public com.strongsalt.strongdoc.sdk.proto.Search.SearchReq getDefaultInstanceForType() {
        return com.strongsalt.strongdoc.sdk.proto.Search.SearchReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.strongsalt.strongdoc.sdk.proto.Search.SearchReq build() {
        com.strongsalt.strongdoc.sdk.proto.Search.SearchReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.strongsalt.strongdoc.sdk.proto.Search.SearchReq buildPartial() {
        com.strongsalt.strongdoc.sdk.proto.Search.SearchReq result = new com.strongsalt.strongdoc.sdk.proto.Search.SearchReq(this);
        result.query_ = query_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.strongsalt.strongdoc.sdk.proto.Search.SearchReq) {
          return mergeFrom((com.strongsalt.strongdoc.sdk.proto.Search.SearchReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.strongsalt.strongdoc.sdk.proto.Search.SearchReq other) {
        if (other == com.strongsalt.strongdoc.sdk.proto.Search.SearchReq.getDefaultInstance()) return this;
        if (!other.getQuery().isEmpty()) {
          query_ = other.query_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.strongsalt.strongdoc.sdk.proto.Search.SearchReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.strongsalt.strongdoc.sdk.proto.Search.SearchReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object query_ = "";
      /**
       * <pre>
       * The search query.
       * </pre>
       *
       * <code>string query = 1;</code>
       * @return The query.
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The search query.
       * </pre>
       *
       * <code>string query = 1;</code>
       * @return The bytes for query.
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The search query.
       * </pre>
       *
       * <code>string query = 1;</code>
       * @param value The query to set.
       * @return This builder for chaining.
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The search query.
       * </pre>
       *
       * <code>string query = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuery() {
        
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The search query.
       * </pre>
       *
       * <code>string query = 1;</code>
       * @param value The bytes for query to set.
       * @return This builder for chaining.
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        query_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.SearchReq)
    }

    // @@protoc_insertion_point(class_scope:proto.SearchReq)
    private static final com.strongsalt.strongdoc.sdk.proto.Search.SearchReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.strongsalt.strongdoc.sdk.proto.Search.SearchReq();
    }

    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchReq>
        PARSER = new com.google.protobuf.AbstractParser<SearchReq>() {
      @java.lang.Override
      public SearchReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.strongsalt.strongdoc.sdk.proto.Search.SearchReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SearchResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The search hits.
     * </pre>
     *
     * <code>repeated .proto.DocumentResult hits = 1;</code>
     */
    java.util.List<com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult> 
        getHitsList();
    /**
     * <pre>
     * The search hits.
     * </pre>
     *
     * <code>repeated .proto.DocumentResult hits = 1;</code>
     */
    com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult getHits(int index);
    /**
     * <pre>
     * The search hits.
     * </pre>
     *
     * <code>repeated .proto.DocumentResult hits = 1;</code>
     */
    int getHitsCount();
    /**
     * <pre>
     * The search hits.
     * </pre>
     *
     * <code>repeated .proto.DocumentResult hits = 1;</code>
     */
    java.util.List<? extends com.strongsalt.strongdoc.sdk.proto.Search.DocumentResultOrBuilder> 
        getHitsOrBuilderList();
    /**
     * <pre>
     * The search hits.
     * </pre>
     *
     * <code>repeated .proto.DocumentResult hits = 1;</code>
     */
    com.strongsalt.strongdoc.sdk.proto.Search.DocumentResultOrBuilder getHitsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.SearchResp}
   */
  public  static final class SearchResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SearchResp)
      SearchRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchResp.newBuilder() to construct.
    private SearchResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchResp() {
      hits_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                hits_ = new java.util.ArrayList<com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult>();
                mutable_bitField0_ |= 0x00000001;
              }
              hits_.add(
                  input.readMessage(com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          hits_ = java.util.Collections.unmodifiableList(hits_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_SearchResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_SearchResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.strongsalt.strongdoc.sdk.proto.Search.SearchResp.class, com.strongsalt.strongdoc.sdk.proto.Search.SearchResp.Builder.class);
    }

    public static final int HITS_FIELD_NUMBER = 1;
    private java.util.List<com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult> hits_;
    /**
     * <pre>
     * The search hits.
     * </pre>
     *
     * <code>repeated .proto.DocumentResult hits = 1;</code>
     */
    public java.util.List<com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult> getHitsList() {
      return hits_;
    }
    /**
     * <pre>
     * The search hits.
     * </pre>
     *
     * <code>repeated .proto.DocumentResult hits = 1;</code>
     */
    public java.util.List<? extends com.strongsalt.strongdoc.sdk.proto.Search.DocumentResultOrBuilder> 
        getHitsOrBuilderList() {
      return hits_;
    }
    /**
     * <pre>
     * The search hits.
     * </pre>
     *
     * <code>repeated .proto.DocumentResult hits = 1;</code>
     */
    public int getHitsCount() {
      return hits_.size();
    }
    /**
     * <pre>
     * The search hits.
     * </pre>
     *
     * <code>repeated .proto.DocumentResult hits = 1;</code>
     */
    public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult getHits(int index) {
      return hits_.get(index);
    }
    /**
     * <pre>
     * The search hits.
     * </pre>
     *
     * <code>repeated .proto.DocumentResult hits = 1;</code>
     */
    public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResultOrBuilder getHitsOrBuilder(
        int index) {
      return hits_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < hits_.size(); i++) {
        output.writeMessage(1, hits_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < hits_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, hits_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.strongsalt.strongdoc.sdk.proto.Search.SearchResp)) {
        return super.equals(obj);
      }
      com.strongsalt.strongdoc.sdk.proto.Search.SearchResp other = (com.strongsalt.strongdoc.sdk.proto.Search.SearchResp) obj;

      if (!getHitsList()
          .equals(other.getHitsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHitsCount() > 0) {
        hash = (37 * hash) + HITS_FIELD_NUMBER;
        hash = (53 * hash) + getHitsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.strongsalt.strongdoc.sdk.proto.Search.SearchResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SearchResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SearchResp)
        com.strongsalt.strongdoc.sdk.proto.Search.SearchRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_SearchResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_SearchResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.strongsalt.strongdoc.sdk.proto.Search.SearchResp.class, com.strongsalt.strongdoc.sdk.proto.Search.SearchResp.Builder.class);
      }

      // Construct using com.strongsalt.strongdoc.sdk.proto.Search.SearchResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHitsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (hitsBuilder_ == null) {
          hits_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          hitsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_SearchResp_descriptor;
      }

      @java.lang.Override
      public com.strongsalt.strongdoc.sdk.proto.Search.SearchResp getDefaultInstanceForType() {
        return com.strongsalt.strongdoc.sdk.proto.Search.SearchResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.strongsalt.strongdoc.sdk.proto.Search.SearchResp build() {
        com.strongsalt.strongdoc.sdk.proto.Search.SearchResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.strongsalt.strongdoc.sdk.proto.Search.SearchResp buildPartial() {
        com.strongsalt.strongdoc.sdk.proto.Search.SearchResp result = new com.strongsalt.strongdoc.sdk.proto.Search.SearchResp(this);
        int from_bitField0_ = bitField0_;
        if (hitsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            hits_ = java.util.Collections.unmodifiableList(hits_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.hits_ = hits_;
        } else {
          result.hits_ = hitsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.strongsalt.strongdoc.sdk.proto.Search.SearchResp) {
          return mergeFrom((com.strongsalt.strongdoc.sdk.proto.Search.SearchResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.strongsalt.strongdoc.sdk.proto.Search.SearchResp other) {
        if (other == com.strongsalt.strongdoc.sdk.proto.Search.SearchResp.getDefaultInstance()) return this;
        if (hitsBuilder_ == null) {
          if (!other.hits_.isEmpty()) {
            if (hits_.isEmpty()) {
              hits_ = other.hits_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHitsIsMutable();
              hits_.addAll(other.hits_);
            }
            onChanged();
          }
        } else {
          if (!other.hits_.isEmpty()) {
            if (hitsBuilder_.isEmpty()) {
              hitsBuilder_.dispose();
              hitsBuilder_ = null;
              hits_ = other.hits_;
              bitField0_ = (bitField0_ & ~0x00000001);
              hitsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHitsFieldBuilder() : null;
            } else {
              hitsBuilder_.addAllMessages(other.hits_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.strongsalt.strongdoc.sdk.proto.Search.SearchResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.strongsalt.strongdoc.sdk.proto.Search.SearchResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult> hits_ =
        java.util.Collections.emptyList();
      private void ensureHitsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          hits_ = new java.util.ArrayList<com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult>(hits_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResultOrBuilder> hitsBuilder_;

      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public java.util.List<com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult> getHitsList() {
        if (hitsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hits_);
        } else {
          return hitsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public int getHitsCount() {
        if (hitsBuilder_ == null) {
          return hits_.size();
        } else {
          return hitsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult getHits(int index) {
        if (hitsBuilder_ == null) {
          return hits_.get(index);
        } else {
          return hitsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public Builder setHits(
          int index, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult value) {
        if (hitsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHitsIsMutable();
          hits_.set(index, value);
          onChanged();
        } else {
          hitsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public Builder setHits(
          int index, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder builderForValue) {
        if (hitsBuilder_ == null) {
          ensureHitsIsMutable();
          hits_.set(index, builderForValue.build());
          onChanged();
        } else {
          hitsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public Builder addHits(com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult value) {
        if (hitsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHitsIsMutable();
          hits_.add(value);
          onChanged();
        } else {
          hitsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public Builder addHits(
          int index, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult value) {
        if (hitsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHitsIsMutable();
          hits_.add(index, value);
          onChanged();
        } else {
          hitsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public Builder addHits(
          com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder builderForValue) {
        if (hitsBuilder_ == null) {
          ensureHitsIsMutable();
          hits_.add(builderForValue.build());
          onChanged();
        } else {
          hitsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public Builder addHits(
          int index, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder builderForValue) {
        if (hitsBuilder_ == null) {
          ensureHitsIsMutable();
          hits_.add(index, builderForValue.build());
          onChanged();
        } else {
          hitsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public Builder addAllHits(
          java.lang.Iterable<? extends com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult> values) {
        if (hitsBuilder_ == null) {
          ensureHitsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hits_);
          onChanged();
        } else {
          hitsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public Builder clearHits() {
        if (hitsBuilder_ == null) {
          hits_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          hitsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public Builder removeHits(int index) {
        if (hitsBuilder_ == null) {
          ensureHitsIsMutable();
          hits_.remove(index);
          onChanged();
        } else {
          hitsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder getHitsBuilder(
          int index) {
        return getHitsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResultOrBuilder getHitsOrBuilder(
          int index) {
        if (hitsBuilder_ == null) {
          return hits_.get(index);  } else {
          return hitsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public java.util.List<? extends com.strongsalt.strongdoc.sdk.proto.Search.DocumentResultOrBuilder> 
           getHitsOrBuilderList() {
        if (hitsBuilder_ != null) {
          return hitsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hits_);
        }
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder addHitsBuilder() {
        return getHitsFieldBuilder().addBuilder(
            com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.getDefaultInstance());
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder addHitsBuilder(
          int index) {
        return getHitsFieldBuilder().addBuilder(
            index, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.getDefaultInstance());
      }
      /**
       * <pre>
       * The search hits.
       * </pre>
       *
       * <code>repeated .proto.DocumentResult hits = 1;</code>
       */
      public java.util.List<com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder> 
           getHitsBuilderList() {
        return getHitsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResultOrBuilder> 
          getHitsFieldBuilder() {
        if (hitsBuilder_ == null) {
          hitsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResultOrBuilder>(
                  hits_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          hits_ = null;
        }
        return hitsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.SearchResp)
    }

    // @@protoc_insertion_point(class_scope:proto.SearchResp)
    private static final com.strongsalt.strongdoc.sdk.proto.Search.SearchResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.strongsalt.strongdoc.sdk.proto.Search.SearchResp();
    }

    public static com.strongsalt.strongdoc.sdk.proto.Search.SearchResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchResp>
        PARSER = new com.google.protobuf.AbstractParser<SearchResp>() {
      @java.lang.Override
      public SearchResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.strongsalt.strongdoc.sdk.proto.Search.SearchResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DocumentResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.DocumentResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The document ID that contains the query terms.
     * </pre>
     *
     * <code>string docID = 1;</code>
     * @return The docID.
     */
    java.lang.String getDocID();
    /**
     * <pre>
     * The document ID that contains the query terms.
     * </pre>
     *
     * <code>string docID = 1;</code>
     * @return The bytes for docID.
     */
    com.google.protobuf.ByteString
        getDocIDBytes();

    /**
     * <pre>
     * The score of the search result.
     * </pre>
     *
     * <code>double score = 2;</code>
     * @return The score.
     */
    double getScore();
  }
  /**
   * Protobuf type {@code proto.DocumentResult}
   */
  public  static final class DocumentResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.DocumentResult)
      DocumentResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DocumentResult.newBuilder() to construct.
    private DocumentResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DocumentResult() {
      docID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DocumentResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DocumentResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              docID_ = s;
              break;
            }
            case 17: {

              score_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_DocumentResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_DocumentResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.class, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder.class);
    }

    public static final int DOCID_FIELD_NUMBER = 1;
    private volatile java.lang.Object docID_;
    /**
     * <pre>
     * The document ID that contains the query terms.
     * </pre>
     *
     * <code>string docID = 1;</code>
     * @return The docID.
     */
    public java.lang.String getDocID() {
      java.lang.Object ref = docID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        docID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The document ID that contains the query terms.
     * </pre>
     *
     * <code>string docID = 1;</code>
     * @return The bytes for docID.
     */
    public com.google.protobuf.ByteString
        getDocIDBytes() {
      java.lang.Object ref = docID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        docID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private double score_;
    /**
     * <pre>
     * The score of the search result.
     * </pre>
     *
     * <code>double score = 2;</code>
     * @return The score.
     */
    public double getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDocIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, docID_);
      }
      if (score_ != 0D) {
        output.writeDouble(2, score_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDocIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, docID_);
      }
      if (score_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, score_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult)) {
        return super.equals(obj);
      }
      com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult other = (com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult) obj;

      if (!getDocID()
          .equals(other.getDocID())) return false;
      if (java.lang.Double.doubleToLongBits(getScore())
          != java.lang.Double.doubleToLongBits(
              other.getScore())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOCID_FIELD_NUMBER;
      hash = (53 * hash) + getDocID().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getScore()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DocumentResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.DocumentResult)
        com.strongsalt.strongdoc.sdk.proto.Search.DocumentResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_DocumentResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_DocumentResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.class, com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.Builder.class);
      }

      // Construct using com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        docID_ = "";

        score_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.strongsalt.strongdoc.sdk.proto.Search.internal_static_proto_DocumentResult_descriptor;
      }

      @java.lang.Override
      public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult getDefaultInstanceForType() {
        return com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult build() {
        com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult buildPartial() {
        com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult result = new com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult(this);
        result.docID_ = docID_;
        result.score_ = score_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult) {
          return mergeFrom((com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult other) {
        if (other == com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult.getDefaultInstance()) return this;
        if (!other.getDocID().isEmpty()) {
          docID_ = other.docID_;
          onChanged();
        }
        if (other.getScore() != 0D) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object docID_ = "";
      /**
       * <pre>
       * The document ID that contains the query terms.
       * </pre>
       *
       * <code>string docID = 1;</code>
       * @return The docID.
       */
      public java.lang.String getDocID() {
        java.lang.Object ref = docID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          docID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The document ID that contains the query terms.
       * </pre>
       *
       * <code>string docID = 1;</code>
       * @return The bytes for docID.
       */
      public com.google.protobuf.ByteString
          getDocIDBytes() {
        java.lang.Object ref = docID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          docID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The document ID that contains the query terms.
       * </pre>
       *
       * <code>string docID = 1;</code>
       * @param value The docID to set.
       * @return This builder for chaining.
       */
      public Builder setDocID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        docID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The document ID that contains the query terms.
       * </pre>
       *
       * <code>string docID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDocID() {
        
        docID_ = getDefaultInstance().getDocID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The document ID that contains the query terms.
       * </pre>
       *
       * <code>string docID = 1;</code>
       * @param value The bytes for docID to set.
       * @return This builder for chaining.
       */
      public Builder setDocIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        docID_ = value;
        onChanged();
        return this;
      }

      private double score_ ;
      /**
       * <pre>
       * The score of the search result.
       * </pre>
       *
       * <code>double score = 2;</code>
       * @return The score.
       */
      public double getScore() {
        return score_;
      }
      /**
       * <pre>
       * The score of the search result.
       * </pre>
       *
       * <code>double score = 2;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(double value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The score of the search result.
       * </pre>
       *
       * <code>double score = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        
        score_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.DocumentResult)
    }

    // @@protoc_insertion_point(class_scope:proto.DocumentResult)
    private static final com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult();
    }

    public static com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DocumentResult>
        PARSER = new com.google.protobuf.AbstractParser<DocumentResult>() {
      @java.lang.Override
      public DocumentResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DocumentResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DocumentResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DocumentResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.strongsalt.strongdoc.sdk.proto.Search.DocumentResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SearchReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SearchReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SearchResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SearchResp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DocumentResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DocumentResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014search.proto\022\005proto\032,protoc-gen-swagge" +
      "r/options/annotations.proto\"N\n\tSearchReq" +
      "\022\r\n\005query\030\001 \001(\t:2\222A/\n\013*\tSearchReq2 \022\036{\"q" +
      "uery\": \"ukraine documents\"}\"\202\001\n\nSearchRe" +
      "sp\022#\n\004hits\030\001 \003(\0132\025.proto.DocumentResult:" +
      "O\222AL\n\014*\nSearchResp2<\022:{\"hits\": [{\"docID\"" +
      ": \"biden_investigation\", \"score\": 100}]}" +
      "\".\n\016DocumentResult\022\r\n\005docID\030\001 \001(\t\022\r\n\005sco" +
      "re\030\002 \001(\001B/\n\"com.strongsalt.strongdoc.sdk" +
      ".protoB\006Search\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.gateway.protoc_gen_swagger.options.Annotations.getDescriptor(),
        });
    internal_static_proto_SearchReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_SearchReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SearchReq_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_proto_SearchResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SearchResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SearchResp_descriptor,
        new java.lang.String[] { "Hits", });
    internal_static_proto_DocumentResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_DocumentResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DocumentResult_descriptor,
        new java.lang.String[] { "DocID", "Score", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(grpc.gateway.protoc_gen_swagger.options.Annotations.openapiv2Schema);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    grpc.gateway.protoc_gen_swagger.options.Annotations.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
